name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    tags:
      - "*.*"
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v4

      - name: Run the script
        run: |
          chmod +x *.sh
          ./start.sh
