name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    tags:
      - "*.*"
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4

      - name: Check License
        run: |
          make check-license 

      - name: Run script
        run: |
          chmod +x *.sh
          ./start.sh
